version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - .:/app
      - /var/app
      # socketファイルの共有
      - sockets:/app/tmp/sockets
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - WEBPACKER_DEV_SERVER_HOST=app
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
      #socketファイルの共有
    volumes: 
      - sockets:/app/tmp/sockets
    depends_on:
      - app

volumes:
  db_data:
  sockets: