version: '2'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/factory
      - /var/factory
      # socketファイルの共有
      - sockets:/factory/tmp/sockets
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - public-data:/factory/public
      - tmp-data:/factory/tmp
    ports:
      - 80:80
      #socketファイルの共有
    volumes: 
      - sockets:/factory/tmp/sockets
    depends_on:
      - app

volumes:
  db_data:
  sockets: