default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  # 以下コメントアウトによりEC2が起動
  # host: db

development:
  <<: *default
  database: factory_development

test:
  <<: *default
  database: factory_test

production:
  <<: *default
  # database: <%= ENV['DB_DATABASE'] %>
  # adapter: mysql2
  # encoding: utf8mb4
  # charset: utf8mb4
  # collation: utf8mb4_general_ci
  # host: <%= ENV['DB_HOST'] %>
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>

  # EC2起動確認済み設定
  database: factory_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock